Update main2.yml

diff --git a/.github/workflows/main2.yml b/.github/workflows/main2.yml
--- a/.github/workflows/main2.yml
+++ b/.github/workflows/main2.yml
@@ -1,43 +1,43 @@
-name: Nodejs
+# name: Nodejs
 
-on:
-  push:
-    branches: ["main"]
-  schedule:
-    - cron: "15 */1 * * *"
-  workflow_dispatch:
+# on:
+#   push:
+#     branches: ["main"]
+#   schedule:
+#     - cron: "15 */1 * * *"
+#   workflow_dispatch:
 
-jobs:
-  build:
-    runs-on: ubuntu-latest
+# jobs:
+#   build:
+#     runs-on: ubuntu-latest
 
-    steps:
-      - name: Checkout código
-        uses: actions/checkout@v4
+#     steps:
+#       - name: Checkout código
+#         uses: actions/checkout@v4
 
-      - name: Configurar Node.js
-        uses: actions/setup-node@v4
-        with:
-          node-version: "20"
+#       - name: Configurar Node.js
+#         uses: actions/setup-node@v4
+#         with:
+#           node-version: "20"
 
-      - name: Instalar dependências
-        run: npm ci
+#       - name: Instalar dependências
+#         run: npm ci
 
-      - name: Executar node index.js
-        env:
-          URL: ${{ secrets.URL }}
-          URL_BROWSER: ${{ secrets.URL_BROWSER }}
-          LOGIN: ${{ secrets.LOGIN }}
-          REF: ${{ secrets.REF }}
-          MINUTOS: ${{ secrets.MINUTOS }}
-          MAX_RETRIES: ${{ secrets.MAX_RETRIES }}
-        timeout-minutes: 30
-        continue-on-error: true
-        run: xvfb-run --auto-servernum -- node --trace-warnings index.js
+#       - name: Executar node index.js
+#         env:
+#           URL: ${{ secrets.URL }}
+#           URL_BROWSER: ${{ secrets.URL_BROWSER }}
+#           LOGIN: ${{ secrets.LOGIN }}
+#           REF: ${{ secrets.REF }}
+#           MINUTOS: ${{ secrets.MINUTOS }}
+#           MAX_RETRIES: ${{ secrets.MAX_RETRIES }}
+#         timeout-minutes: 30
+#         continue-on-error: true
+#         run: xvfb-run --auto-servernum -- node --trace-warnings index.js
 
-      - name: Upload da captura
-        uses: actions/upload-artifact@v4
-        if: success() || failure()
-        with:
-          name: screenshot
-          path: screen.png
+#       - name: Upload da captura
+#         uses: actions/upload-artifact@v4
+#         if: success() || failure()
+#         with:
+#           name: screenshot
+#           path: screen.png
